// Especificaciones de niveles procedurales (Mov. I).
// Layout actual: LevelGenerator rectangular; objetivo: docs/PROCEDURAL_LEVELS.md.
export const LEVELS = [
  {
    name: 'La Entrada',
    cols: 45,
    rows: 33,
    destructibleChance: 0.35,
    enemies: 0,
    enemyKinds: [],
    bgMusic: 'world1',
  },
  {
    name: 'Las Herramientas',
    cols: 45,
    rows: 33,
    destructibleChance: 0.4,
    enemies: 0,
    enemyKinds: [],
    bgMusic: 'world1',
  },
  {
    name: 'La Profundidad',
    cols: 51,
    rows: 37,
    destructibleChance: 0.45,
    enemies: 4,
    enemyKinds: ['golem_basic'],
    bgMusic: 'world1',
  },
  {
    name: 'Los Habitantes',
    cols: 51,
    rows: 37,
    destructibleChance: 0.46,
    enemies: 6,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Recolección',
    cols: 51,
    rows: 37,
    destructibleChance: 0.48,
    enemies: 8,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Cámara Antigua',
    cols: 57,
    rows: 41,
    destructibleChance: 0.5,
    enemies: 10,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    bgMusic: 'world1',
  },
  {
    name: 'El Primer Excavador',
    cols: 57,
    rows: 41,
    destructibleChance: 0.52,
    enemies: 12,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    bgMusic: 'world1',
  },
]
