// Especificaciones del grafo procedural (Mov. I).
// `nodeSizes` no incluye la cámara pequeña de entrada, que el generador añade siempre.
export const LEVELS = [
  {
    name: 'La Entrada',
    nodeSizes: ['small'],
    extraCycles: [0, 0],
    resourceCap: 0,
    enemies: 0,
    enemyKinds: [],
    bgMusic: 'world1',
  },
  {
    name: 'Las Herramientas',
    nodeSizes: ['small', 'small', 'small'],
    extraCycles: [0, 0],
    resourceCap: 9,
    enemies: 0,
    enemyKinds: [],
    bgMusic: 'world1',
  },
  {
    name: 'La Profundidad',
    nodeCount: [4, 5],
    fixedNodeSizes: ['small', 'small'],
    fillNodeSize: 'medium',
    extraCycles: [0, 1],
    resourceCap: 12,
    crystalCap: 2,
    recipeFragments: 1,
    enemies: 4,
    enemyKinds: ['golem_basic'],
    bgMusic: 'world1',
  },
  {
    name: 'Los Habitantes',
    nodeCount: [4, 5],
    fixedNodeSizes: ['small', 'small'],
    fillNodeSize: 'medium',
    extraCycles: [0, 1],
    resourceCap: 14,
    enemies: 6,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Recolección',
    nodeSizes: ['small', 'small', 'small', 'medium', 'medium', 'medium'],
    extraCycles: [1, 2],
    resourceCap: 16,
    recipeFragments: 1,
    enemies: 8,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Cámara Antigua',
    nodeSizes: ['small', 'small', 'small', 'medium', 'medium', 'medium', 'large'],
    extraCycles: [1, 2],
    resourceCap: 14,
    recipeFragments: 1,
    enemies: 10,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    bgMusic: 'world1',
  },
  {
    name: 'El Primer Excavador',
    nodeSizes: [
      'small', 'small', 'small',
      'medium', 'medium', 'medium',
      'large', 'large',
    ],
    extraCycles: [1, 2],
    resourceCap: 10,
    enemies: 12,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    timeLimit: 180,
    bgMusic: 'world1',
  },
]
