// Especificaciones del grafo procedural (Mov. I).
// `nodeSizes` no incluye la cámara pequeña de entrada, que el generador añade siempre.
export const LEVELS = [
  {
    name: 'La Entrada',
    nodeSizes: ['small'],
    extraCycles: [0, 0],
    resourceCap: 0,
    enemies: 0,
    enemyKinds: [],
    emptyTileLight: 10,
    bgMusic: 'world1',
  },
  {
    name: 'Las Herramientas',
    nodeSizes: ['small', 'small', 'small'],
    extraCycles: [0, 0],
    resourceCap: 9,
    enemies: 0,
    enemyKinds: [],
    emptyTileLight: 10,
    bgMusic: 'world1',
  },
  {
    name: 'La Profundidad',
    nodeCount: [4, 5],
    fixedNodeSizes: ['small', 'small'],
    fillNodeSize: 'medium',
    extraCycles: [0, 1],
    resourceCap: 12,
    crystalCap: 2,
    fragmentSlots: [{ rank: 2, kind: 'generic' }],
    enemies: 4,
    enemyKinds: ['golem_basic'],
    bgMusic: 'world1',
  },
  {
    name: 'Los Habitantes',
    nodeCount: [4, 5],
    fixedNodeSizes: ['small', 'small'],
    fillNodeSize: 'medium',
    extraCycles: [0, 1],
    resourceCap: 14,
    fragmentSlots: [{ rank: 2, kind: 'generic' }],
    enemies: 6,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Recolección',
    nodeSizes: ['small', 'small', 'small', 'medium', 'medium', 'medium'],
    extraCycles: [1, 2],
    resourceCap: 16,
    fragmentSlots: [
      { rank: 2, kind: 'generic' },
      { rank: 2, kind: 'generic' },
    ],
    puzzle: {
      count: 3,
      reward: { bronze: 3, iron: 2, crystal: 1 },
    },
    enemies: 8,
    enemyKinds: ['golem_basic', 'spirit'],
    bgMusic: 'world1',
  },
  {
    name: 'La Cámara Antigua',
    nodeSizes: ['small', 'small', 'small', 'medium', 'medium', 'medium', 'large'],
    extraCycles: [1, 2],
    resourceCap: 14,
    fragmentSlots: [
      { rank: 3, kind: 'specialized' },
      { rank: 3, kind: 'specialized' },
      { rank: 3, kind: 'specialized' },
    ],
    puzzle: {
      count: 4,
      reward: { bronze: 4, iron: 3, crystal: 2 },
    },
    enemies: 10,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    bgMusic: 'world1',
  },
  {
    name: 'El Primer Excavador',
    nodeSizes: [
      'small', 'small', 'small',
      'medium', 'medium', 'medium',
      'large', 'large',
    ],
    extraCycles: [1, 2],
    resourceCap: 10,
    trapCap: 4,
    enemies: 12,
    enemyKinds: ['golem_basic', 'spirit', 'golem_advanced'],
    timeLimit: 180,
    bgMusic: 'world1',
  },
]
